name: Swift

on:
  push:
    branches: [development, develop]
  pull_request:
    branches: [development, develop]

jobs:
  Xcode:
    strategy:
      fail-fast: false
      matrix:
        xcode_version: ['16.2']
    runs-on: macos-14
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app
    steps:
      - uses: actions/checkout@v2
      - run: swift -version
      - run: swift test -c release -Xswiftc -enable-testing

  Linux:
    # Linux is disabled for this fork
    if: false
    strategy:
      fail-fast: false
      matrix:
        tag: ['5.10']
    runs-on: ubuntu-latest
    container:
      image: swift:${{ matrix.tag }}
    steps:
      - uses: actions/checkout@v2
      - run: swift test -c release -Xswiftc -enable-testing
